# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.

# Basic Site Settings
locale                   : "en-US"
title                    : "Sunyan Wang"
title_separator          : "-"
name                     : "Sunyan Wang"
description              : "Personal academic website of Sunyan Wang, an undergraduate at Tsinghua University researching AI Agents." # MODIFIED: Updated description
url                      : "https://wangsunyan777.github.io" # IMPORTANT: Please double-check this is your correct GitHub Pages URL.
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "wangsunyan777/wangsunyan777.github.io" # IMPORTANT: Please double-check this is your correct repository name.

# Site Author - The following control what appear as part of the author content on the side bar.
author:
  # Biographic information
  avatar           : "images/profile.png" # NOTE: Make sure you have a 'profile.png' file in the 'images' folder.
  name             : "Sunyan Wang"
  # pronouns         : "he/him" # You can uncomment this if you wish
  bio              : "Undergraduate at Tsinghua University, researching AI Agents." # MODIFIED: A concise bio for the sidebar.
  location         : "Beijing, China"
  employer         : 
  uri              : "https://wangsunyan777.github.io"
  email            : "wangsuny24@mails.tsinghua.edu.cn" 

  # Academic websites - Commented out until you have publications.
  # academia         : 
  # arxiv            : 
  # googlescholar    : 
  # orcid            : 

  # Repositories and software development
  github           : "wangsunyan777" # MODIFIED: Your GitHub username
  
  # Social media - All commented out for a cleaner look. You can add them back later.
  # linkedin         :
  # twitter          :
  # zhihu            :

# Publication Category - No changes needed here for now
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'    
  conferences:
    title: 'Conference Papers'

# --- The rest of the file remains largely the same, no need to edit below this line unless for advanced customization ---

# Site Settings
teaser                   :
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"
talkmap_link             : false
comments:
  provider               : false

# Analytics
analytics:
  provider               : false
  
# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: Etc/UTC

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Mimic GitHub Pages with --safe
whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
